# Generated by Django 4.2 on 2024-01-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='screenshots/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('w', 'web'), ('a', 'application'), ('e', 'else')], default='w', max_length=1)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('purpose', models.TextField()),
                ('icon', models.ImageField(upload_to='project_icons/')),
                ('repository', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(default='', max_length=20)),
                ('description_en', models.TextField(default='')),
                ('purpose_en', models.TextField(default='')),
                ('screenshots', models.ManyToManyField(to='api.screenshot')),
            ],
        ),
    ]
